name: Python application test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Python script and save output
      run: |
        python avl_tree.py > output_program.txt
    - name: Commit and push changes
      run: |
        git config --global user.name 'luqyanaaribawa1'
        git config --global user.email 'luqyanaaribawa70@gmail.com'
        git add output_program.txt
        git commit -m "Add output_program1.txt"
        git push https://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@github.com/luqyanaaribawa1/TUGAS_M11_StrukturData
